# Generated by Django 3.2.6 on 2021-10-23 17:55

import adds.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='a8sam1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('namex', models.CharField(max_length=100)),
                ('svg', models.FileField(null=True, upload_to='pictures/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])])),
            ],
        ),
        migrations.CreateModel(
            name='add_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.CharField(max_length=5)),
                ('phone', models.CharField(default='', max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='Length has to be 10', regex='^.{10}$')])),
                ('image', models.ImageField(upload_to=adds.models.image_upload)),
                ('cate', models.CharField(choices=[('شاليهات', 'شاليهات'), ('مخيمات', 'مخيمات'), ('قوارب صيد', 'قوارب صيد'), ('قوارب نزهة', 'قوارب نزهة')], max_length=15)),
                ('city', models.CharField(choices=[('جدة', 'جدة'), ('الرياض', 'الرياض')], max_length=15)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('img1', models.ImageField(blank=True, upload_to=adds.models.image_upload)),
                ('img2', models.ImageField(blank=True, upload_to=adds.models.image_upload)),
                ('img3', models.ImageField(blank=True, upload_to=adds.models.image_upload)),
                ('img4', models.ImageField(blank=True, upload_to=adds.models.image_upload)),
            ],
        ),
    ]
