# Generated by Django 3.2.6 on 2021-10-23 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_detail',
            name='cate',
        ),
    ]
