# Generated by Django 3.2.6 on 2021-10-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0003_add_detail_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a8sam1',
            name='title',
            field=models.CharField(choices=[('شاليهات', 'شاليهات'), ('مخيمات', 'مخيمات'), ('قوارب صيد', 'قوارب صيد'), ('قوارب نزهة', 'قوارب نزهة')], max_length=15),
        ),
    ]
