# Generated by Django 3.2.6 on 2021-10-23 20:17

import adds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adds', '0005_auto_20211023_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a8sam1',
            name='svg',
        ),
        migrations.AddField(
            model_name='a8sam1',
            name='icon',
            field=models.ImageField(default='', upload_to=adds.models.image_upload),
            preserve_default=False,
        ),
    ]
